### ISSUE TITLE
Frozen Projectiles? Wha?

### ISSUE THREAD

**Issue by HyperMan19680** [2piradians/Minewatch#1] opened 2017-10-21 16:31 UTC
I was testing the latest update of Minewatch and found my projectiles from the guns that I tried, Junkrat's Frag Launcher, and Mercy's Caedaus Blaster, weren't moving after spawning in via their guns. They still damage, but only if they are run into by a mob.

**Comment by Furgl** [comment] 2017-10-21 18:13
Try relogging and see if that fixes the issue. If you can get this to happen consistently, please let us know and we will work on fixing it.

Can you also tell us what Minecraft / Forge versions you're using?

**Comment by HyperMan19680** [comment] 2017-10-22 01:29
I did it on 1.12.2, forge version 2515.

Also other projectiles like the vanilla Bow are not stopped from moving, so it's definitely something with your mod.

**Comment by 2piradians** [comment] 2017-10-22 01:33
"I did it on 1.12.2,"
Did you try re-logging like Furgl suggested? What were the results?

**Comment by HyperMan19680** [comment] 2017-10-22 01:48
I have, and same results.

Or do you mean relog my computer? If so, not yet, I merely relogged my game.

**Comment by Furgl** [comment] 2017-10-22 01:59
I've loaded up 1.12.2 with Forge 2515 as well and haven't been able to replicate this. Have you tried restarting Minecraft and / or tried this on a brand new world? Do you have any other mods installed as well? What Java version are you using? Is this single-player or multi-player?

**Comment by 2piradians** [comment] 2017-10-22 02:09
I have also tested on 1.12.2 using Forge 2515, including brand new setup, freshly created so nothing would interfere. I could not replicate this.

**Comment by Furgl** [comment] 2017-10-22 02:15
We've encountered a similar bug before with previous versions and we'd like to fix it, but we need to have a way to consistently recreate it to test it and find a fix.

**Comment by HyperMan19680** [comment] 2017-10-22 13:13
I'm using Java 8, and yes I do have other mods installed. Too many to list at the moment, maybe I can package them up somehow.

I also tried Junkrat in a new world, the same result. Projectiles hung in the air.

**Comment by 2piradians** [comment] 2017-10-22 14:11
"I also tried Junkrat in a new world"
Did you try this with only Minewatch or all of your other mods? If not alone, can you replicate this with only Minewatch installed?

**Comment by Furgl** [comment] 2017-10-22 14:28
This is likely caused by interference with another mod. If you can narrow down which mod(s) are causing it (easy way would be to remove half of the other mods and retest, then repeat), or if you have the modpack that we can download, we can try to fix it.

**Comment by HyperMan19680** [comment] 2017-10-22 14:33
I'm uploading my modpack to Dropbox right now, in the form of a .zip file. I'll edit with the link once I see it's uploaded.

EDIT: Up and Loaded! https://www.dropbox.com/s/7qolupougp7fcqr/1.12.2.zip?dl=0

**Comment by Furgl** [comment] 2017-10-22 19:49
This should be fixed in v3.4.1: https://minecraft.curseforge.com/projects/minewatch/files/2493268
Thank you for reporting it!

**Closed as completed by Furgl** 2017-10-22 19:49 UTC
